// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

#if os(iOS) || os(tvOS) || os(watchOS)
  import UIKit.UIImage
  typealias Image = UIImage
#elseif os(OSX)
  import AppKit.NSImage
  typealias Image = NSImage
#endif

// swiftlint:disable file_length
// swiftlint:disable type_body_length
enum Asset: String {
  case Page1 = "page1"
  case Page2 = "page2"
  case Page3 = "page3"
  case Pageopen = "pageopen"
  case Qdy = "qdy"
  case AppIcon = "appIcon"
  case Chacha = "chacha"
  case Dachanzi = "dachanzi"
  case Distance = "distance"
  case DistanceH = "distanceH"
  case Email = "email"
  case EmailG = "emailG"
  case EmailGNew = "emailGNew"
  case Erweima = "erweima"
  case HomeBGMiddle = "homeBGMiddle"
  case HomeBGNav = "homeBGNav"
  case Homeround = "homeround"
  case Hot = "hot"
  case HotH = "hotH"
  case Huolibi = "huolibi"
  case HuolibiH = "huolibiH"
  case LazyDig = "lazyDig"
  case Lpqtx = "lpqtx"
  case Or = "or"
  case Qiuqiu = "qiuqiu"
  case Question = "question"
  case Questionxia = "questionxia"
  case Questionyou = "questionyou"
  case Rocket = "rocket"
  case RocketWhite = "rocketWhite"
  case Share = "share"
  case ShareBg = "shareBg"
  case Activity = "activity"
  case Ad_text = "ad_text"
  case Ggl = "ggl"
  case HDshang = "HDshang"
  case HDxia = "HDxia"
  case Hu = "hu"
  case Invite = "invite"
  case Jiang_Hei = "jiang-hei"
  case Jiang = "jiang"
  case Lepaoquan_g = "lepaoquan_g"
  case Lepaoquan_h = "lepaoquan_h"
  case Lepaoquan_white = "lepaoquan_white"
  case Scratch = "scratch"
  case ScratchAd = "scratchAd"
  case Yqhy = "yqhy"
  case LoginBig = "loginBig"
  case Tongyi = "tongyi"
  case Weitongyi = "weitongyi"
  case Eyes = "eyes"
  case HeadImge = "headImge"
  case LepaoLogo = "lepaoLogo"
  case Mima = "mima"
  case Mine = "mine"
  case Right = "right"
  case UserImg = "userImg"
  case VIP = "VIP"
  case Wueyes = "wueyes"
  case Back = "back"
  case Cha = "cha"
  case Dayou = "dayou"
  case Dazuo = "dazuo"
  case Fenxiang = "fenxiang"
  case Riqi = "riqi"
  case You_1 = "you-1"
  case You = "you"
  case YouGray = "youGray"
  case Zuo = "zuo"
  case Qq_c = "qq_c"
  case ShareAppicon = "shareAppicon"
  case Sina_weibo_c = "sina_weibo_c"
  case Wechat_c = "wechat_c"
  case Wechat_moment_c = "wechat_moment_c"
  case Bar1 = "bar1"
  case Bar2 = "bar2"
  case Bar3 = "bar3"
  case Bar4 = "bar4"
  case BarBS1 = "barBS1"
  case BarBS2 = "barBS2"
  case BarBS3 = "barBS3"
  case BarBS4 = "barBS4"
  case BarYe1 = "barYe1"
  case BarYe2 = "barYe2"
  case BarYe3 = "barYe3"
  case BarYe4 = "barYe4"
  case BarYeBS1 = "barYeBS1"
  case BarYeBS2 = "barYeBS2"
  case BarYeBS3 = "barYeBS3"
  case BarYeBS4 = "barYeBS4"
  case Hlb_Wu = "hlb-wu"
  case Hlb = "hlb"
  case Huodong_Wu = "huodong-wu"
  case Huodong = "huodong"
  case Shouye_Wu = "shouye-wu"
  case Shouye = "shouye"
  case Wode_Wu = "wode-wu"
  case Wode = "wode"
  case Change = "change"
  case Diamond = "diamond"
  case Earnings = "earnings"
  case ExchangeH = "exchangeH"
  case Pay = "pay"
  case PayH = "payH"
  case Recordchong = "recordchong"
  case Recordduihuan = "recordduihuan"
  case Recordjibu = "recordjibu"
  case Recordsjkj = "recordsjkj"
  case Recordtixian = "recordtixian"
  case Recordwakuang = "recordwakuang"
  case Recordyqhy = "recordyqhy"
  case ShoukuanH = "shoukuanH"
  case Wallet_2 = "Wallet 2"
  case Wallet = "Wallet"

  var image: Image {
    return Image(asset: self)
  }
}
// swiftlint:enable type_body_length

extension Image {
  convenience init!(asset: Asset) {
    self.init(named: asset.rawValue)
  }
}

